-- seed_monkeys.sql  –  40 einzigartige Affen + 160 feste Traits
BEGIN;

INSERT INTO monkeys (id, name, image_url, rarity, price) VALUES
  ('monk-001','Golden Emperor','assets/monk-001.png','Mythic',9500),
  ('monk-002','Crystal Sage','assets/monk-002.png','Mythic',8800),
  ('monk-003','Shadow Lord','assets/monk-003.png','Mythic',9200),
  ('monk-004','Phoenix King','assets/monk-004.png','Mythic',9800),
  ('monk-005','Royal Guard','assets/monk-005.png','Legendary',4500),
  ('monk-006','Space Explorer','assets/monk-006.png','Legendary',4200),
  ('monk-007','Pirate Captain','assets/monk-007.png','Legendary',3800),
  ('monk-008','Ninja Master','assets/monk-008.png','Legendary',4800),
  ('monk-009','Wizard Sage','assets/monk-009.png','Legendary',4000),
  ('monk-010','Cyber Punk','assets/monk-010.png','Legendary',4600),
  ('monk-011','Forest Ranger','assets/monk-011.png','Epic',2200),
  ('monk-012','Desert Nomad','assets/monk-012.png','Epic',2500),
  ('monk-013','Arctic Explorer','assets/monk-013.png','Epic',2300),
  ('monk-014','Tribal Chief','assets/monk-014.png','Epic',2800),
  ('monk-015','Steampunk Engineer','assets/monk-015.png','Epic',2400),
  ('monk-016','Viking Warrior','assets/monk-016.png','Epic',2700),
  ('monk-017','Samurai Honor','assets/monk-017.png','Epic',2600),
  ('monk-018','Biker Rebel','assets/monk-018.png','Epic',2100),
  ('monk-019','Rockstar','assets/monk-019.png','Epic',2900),
  ('monk-020','Deep Sea Diver','assets/monk-020.png','Epic',2000),
  ('monk-021','Beach Monkey','assets/monk-021.png','Rare',1200),
  ('monk-022','City Dweller','assets/monk-022.png','Rare',1500),
  ('monk-023','Garden Keeper','assets/monk-023.png','Rare',1100),
  ('monk-024','Mountain Climber','assets/monk-024.png','Rare',1400),
  ('monk-025','Chef Supreme','assets/monk-025.png','Rare',1300),
  ('monk-026','Artist Soul','assets/monk-026.png','Rare',1600),
  ('monk-027','Librarian','assets/monk-027.png','Rare',1000),
  ('monk-028','Farmer','assets/monk-028.png','Rare',900),
  ('monk-029','Mechanic','assets/monk-029.png','Rare',1700),
  ('monk-030','Photographer','assets/monk-030.png','Rare',1800),
  ('monk-031','Basic Monkey','assets/monk-031.png','Common',500),
  ('monk-032','Simple Sam','assets/monk-032.png','Common',300),
  ('monk-033','Casual Chris','assets/monk-033.png','Common',400),
  ('monk-034','Regular Rick','assets/monk-034.png','Common',350),
  ('monk-035','Plain Pete','assets/monk-035.png','Common',600),
  ('monk-036','Ordinary Oliver','assets/monk-036.png','Common',450),
  ('monk-037','Standard Steve','assets/monk-037.png','Common',250),
  ('monk-038','Normal Ned','assets/monk-038.png','Common',380),
  ('monk-039','Basic Bob','assets/monk-039.png','Common',550),
  ('monk-040','Common Carl','assets/monk-040.png','Common',320);

INSERT INTO monkey_traits (monkey_id, background, fur, headgear, prop) VALUES
  ('monk-001','Celestial Galaxy','Golden Divine','Crown of Kings','Staff of Power'),
  ('monk-002','Aurora Borealis','Crystal Shimmer','Wisdom Circlet','Ancient Scroll'),
  ('monk-003','Void Darkness','Shadow Smoke','Dark Crown','Soul Blade'),
  ('monk-004','Burning Sky','Phoenix Flame','Fire Crown','Flame Scepter'),
  ('monk-005','Royal Palace','Silver Armor','Knight Helmet','Royal Sword'),
  ('monk-006','Deep Space','Cosmic Silver','Astronaut Helmet','Laser Blaster'),
  ('monk-007','Stormy Seas','Weather Beaten','Captain''s Hat','Treasure Map'),
  ('monk-008','Moonlit Dojo','Shadow Black','Ninja Mask','Katana'),
  ('monk-009','Mystic Forest','Ethereal Blue','Wizard Hat','Magic Wand'),
  ('monk-010','Neon City','Cybernetic','VR Headset','Data Chip'),
  ('monk-011','Ancient Forest','Camouflage Green','Ranger Hat','Wooden Bow'),
  ('monk-012','Sand Dunes','Sandy Brown','Turban','Curved Dagger'),
  ('monk-013','Frozen Tundra','White Frost','Fur Cap','Ice Axe'),
  ('monk-014','Jungle Village','Tribal Paint','Feather Crown','Bone Spear'),
  ('monk-015','Gear Workshop','Copper Tinted','Goggles','Wrench'),
  ('monk-016','Fjord Mountains','Battle Scarred','Horned Helmet','Battle Axe'),
  ('monk-017','Cherry Blossom','Honor Bound','Samurai Helm','Honor Blade'),
  ('monk-018','Highway','Leather Jacket','Bandana','Chain'),
  ('monk-019','Concert Stage','Glitter Silver','Mohawk','Electric Guitar'),
  ('monk-020','Ocean Depths','Wetsuit','Diving Helmet','Treasure Chest'),
  ('monk-021','Tropical Beach','Sun Kissed','Straw Hat','Coconut'),
  ('monk-022','Urban Skyline','Street Style','Baseball Cap','Coffee Cup'),
  ('monk-023','Flower Garden','Moss Green','Sun Hat','Watering Can'),
  ('monk-024','Rocky Peak','Hiking Gear','Climbing Helmet','Rope'),
  ('monk-025','Kitchen','Chef Whites','Chef Hat','Spatula'),
  ('monk-026','Art Studio','Paint Splattered','Beret','Paint Brush'),
  ('monk-027','Ancient Library','Scholarly','Reading Glasses','Old Book'),
  ('monk-028','Wheat Field','Work Worn','Straw Hat','Pitchfork'),
  ('monk-029','Garage','Oil Stained','Work Cap','Wrench'),
  ('monk-030','Photo Studio','Professional','None','Camera'),
  ('monk-031','Plain Blue','Brown','None','Banana'),
  ('monk-032','Green Grass','Light Brown','None','Stick'),
  ('monk-033','Blue Sky','Dark Brown','None','Apple'),
  ('monk-034','Tree Branch','Grey','None','Leaf'),
  ('monk-035','Forest','Tan','None','Twig'),
  ('monk-036','Sunset','Golden Brown','None','Pebble'),
  ('monk-037','Cloudy','Beige','None','Acorn'),
  ('monk-038','Meadow','Cream','None','Flower'),
  ('monk-039','Rocks','Chestnut','None','Stone'),
  ('monk-040','Dirt Path','Rust Brown','None','Mud Ball');

commit;